# Generated by Django 4.1 on 2022-09-06 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoDeCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('bandeira', models.CharField(max_length=50)),
                ('numero', models.PositiveIntegerField()),
                ('nome_titular', models.CharField(max_length=50)),
                ('vencimento_pagamento', models.PositiveIntegerField()),
                ('codigo_seguranca', models.PositiveIntegerField()),
                ('data_validade', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cidade', models.CharField(default='Ubajara', max_length=20)),
                ('estado', models.CharField(choices=[('MT', 'Mato Grosso'), ('PA', 'Pará'), ('ES', 'Espirito Santo'), ('MG', 'Minas Gerais'), ('GO', 'Goiás'), ('DF', 'Distrito Federal'), ('BA', 'Bahia'), ('PI', 'Piauí'), ('RO', 'Rondônia'), ('RS', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('AM', 'Amazonas'), ('CE', 'Ceará'), ('TO', 'Tocantins'), ('MS', 'Mato Grosso do Sul'), ('RJ', 'Rio de Janeiro'), ('AL', 'Alagoas'), ('MA', 'Maranhão'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('AP', 'Amapá'), ('SP', 'São Paulo'), ('PR', 'Parana'), ('RR', 'Roraima'), ('PE', 'Pernambuco'), ('AC', 'Acre'), ('PB', 'Paraíba')], default='CE', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DespesaCartaoDeCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('parcelamento', models.CharField(default=1, max_length=4)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cartaodecredito')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(default=6, max_length=2)),
                ('mes', models.CharField(choices=[('Agosto', 'Agosto'), ('Abril', 'Abril'), ('Janeiro', 'Janeiro'), ('Setembro', 'Setembro'), ('Março', 'Março'), ('Fevereiro', 'Fevereiro'), ('Dezembro', 'Dezembro'), ('Maio', 'Maio'), ('Julho', 'Julho'), ('Outubro', 'Outubro'), ('Novembro', 'Novembro'), ('Junho', 'Junho')], default=9, max_length=15)),
                ('ano', models.CharField(default=2022, max_length=4)),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('parcelamento', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago')], default='Pendente', max_length=8)),
                ('forma_de_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.formapagamento', verbose_name='Forma de Pagamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('caixa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cadastros.caixa')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.categoriareceita')),
            ],
            bases=('cadastros.caixa',),
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('caixa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cadastros.caixa')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.categoriadespesa')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.fornecedor')),
            ],
            bases=('cadastros.caixa',),
        ),
    ]
