# Generated by Django 4.1 on 2022-09-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='mes',
            field=models.CharField(choices=[('Março', 'Março'), ('Outubro', 'Outubro'), ('Janeiro', 'Janeiro'), ('Dezembro', 'Dezembro'), ('Novembro', 'Novembro'), ('Maio', 'Maio'), ('Junho', 'Junho'), ('Agosto', 'Agosto'), ('Fevereiro', 'Fevereiro'), ('Abril', 'Abril'), ('Julho', 'Julho'), ('Setembro', 'Setembro')], default=9, max_length=15),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='status',
            field=models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente')], default='Pendente', max_length=8),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='estado',
            field=models.CharField(choices=[('RR', 'Roraima'), ('RS', 'Rio Grande do Norte'), ('AP', 'Amapá'), ('AC', 'Acre'), ('RO', 'Rondônia'), ('MA', 'Maranhão'), ('ES', 'Espirito Santo'), ('AM', 'Amazonas'), ('RS', 'Rio Grande do Sul'), ('BA', 'Bahia'), ('RJ', 'Rio de Janeiro'), ('PA', 'Pará'), ('MS', 'Mato Grosso do Sul'), ('SC', 'Santa Catarina'), ('DF', 'Distrito Federal'), ('TO', 'Tocantins'), ('AL', 'Alagoas'), ('GO', 'Goiás'), ('PR', 'Parana'), ('PI', 'Piauí'), ('SP', 'São Paulo'), ('MT', 'Mato Grosso'), ('PB', 'Paraíba'), ('MG', 'Minas Gerais'), ('CE', 'Ceará'), ('PE', 'Pernambuco'), ('SE', 'Sergipe')], default='CE', max_length=2),
        ),
    ]
