# Generated by Django 4.1 on 2022-09-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_caixa_mes_alter_caixa_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesacartaodecredito',
            name='fatura',
            field=models.CharField(choices=[('Setembro', 'Setembro'), ('Julho', 'Julho'), ('Dezembro', 'Dezembro'), ('Agosto', 'Agosto'), ('Janeiro', 'Janeiro'), ('Fevereiro', 'Fevereiro'), ('Novembro', 'Novembro'), ('Junho', 'Junho'), ('Maio', 'Maio'), ('Outubro', 'Outubro'), ('Março', 'Março'), ('Abril', 'Abril')], default=9, max_length=20),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='mes',
            field=models.CharField(choices=[('Setembro', 'Setembro'), ('Julho', 'Julho'), ('Dezembro', 'Dezembro'), ('Agosto', 'Agosto'), ('Janeiro', 'Janeiro'), ('Fevereiro', 'Fevereiro'), ('Novembro', 'Novembro'), ('Junho', 'Junho'), ('Maio', 'Maio'), ('Outubro', 'Outubro'), ('Março', 'Março'), ('Abril', 'Abril')], default=9, max_length=15),
        ),
        migrations.AlterField(
            model_name='despesacartaodecredito',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='estado',
            field=models.CharField(choices=[('RJ', 'Rio de Janeiro'), ('SE', 'Sergipe'), ('SC', 'Santa Catarina'), ('AC', 'Acre'), ('MA', 'Maranhão'), ('AL', 'Alagoas'), ('GO', 'Goiás'), ('MT', 'Mato Grosso'), ('SP', 'São Paulo'), ('RO', 'Rondônia'), ('MS', 'Mato Grosso do Sul'), ('RR', 'Roraima'), ('AM', 'Amazonas'), ('CE', 'Ceará'), ('PI', 'Piauí'), ('TO', 'Tocantins'), ('PA', 'Pará'), ('BA', 'Bahia'), ('RS', 'Rio Grande do Sul'), ('MG', 'Minas Gerais'), ('PE', 'Pernambuco'), ('ES', 'Espirito Santo'), ('PB', 'Paraíba'), ('AP', 'Amapá'), ('PR', 'Parana'), ('RS', 'Rio Grande do Norte'), ('DF', 'Distrito Federal')], default='CE', max_length=2),
        ),
    ]
